language: go

services:
  - docker

script:
  - make test

before_deploy:
  - .travis/install_operator_sdk.sh

deploy:
  provider: script
  skip_cleanup: true
  # environment variables are defined in travis ui
  script: bash .travis/docker_push.sh $TRAVIS_TAG $DOCKER_PASSWORD
  on:
    tags: true
