# permissions for end users to edit lastpasses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lastpass-operator
    app.kubernetes.io/managed-by: kustomize
  name: lastpass-editor-role
rules:
- apiGroups:
  - edgelevel.com
  resources:
  - lastpasses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edgelevel.com
  resources:
  - lastpasses/status
  verbs:
  - get
