# permissions for end users to edit lastpassgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: lastpass-operator
    app.kubernetes.io/managed-by: kustomize
  name: lastpassgroup-editor-role
rules:
- apiGroups:
  - edgelevel.com
  resources:
  - lastpassgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - edgelevel.com
  resources:
  - lastpassgroups/status
  verbs:
  - get
