// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ItemRef) DeepCopyInto(out *ItemRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ItemRef.
func (in *ItemRef) DeepCopy() *ItemRef {
	if in == nil {
		return nil
	}
	out := new(ItemRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastPassSecret) DeepCopyInto(out *LastPassSecret) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastPassSecret.
func (in *LastPassSecret) DeepCopy() *LastPassSecret {
	if in == nil {
		return nil
	}
	out := new(LastPassSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LastPassSecret) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastPassSecretList) DeepCopyInto(out *LastPassSecretList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LastPassSecret, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastPassSecretList.
func (in *LastPassSecretList) DeepCopy() *LastPassSecretList {
	if in == nil {
		return nil
	}
	out := new(LastPassSecretList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LastPassSecretList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastPassSecretSpec) DeepCopyInto(out *LastPassSecretSpec) {
	*out = *in
	out.ItemRef = in.ItemRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastPassSecretSpec.
func (in *LastPassSecretSpec) DeepCopy() *LastPassSecretSpec {
	if in == nil {
		return nil
	}
	out := new(LastPassSecretSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LastPassSecretStatus) DeepCopyInto(out *LastPassSecretStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LastPassSecretStatus.
func (in *LastPassSecretStatus) DeepCopy() *LastPassSecretStatus {
	if in == nil {
		return nil
	}
	out := new(LastPassSecretStatus)
	in.DeepCopyInto(out)
	return out
}
