apiVersion: edgelevel.com/v1alpha1
kind: LastPassGroup
metadata:
  labels:
    app.kubernetes.io/name: lastpass-operator
    app.kubernetes.io/managed-by: kustomize
  name: lastpassgroup-sample
spec:
  # TODO(user): Add fields here
