apiVersion: edgelevel.com/v1alpha1
kind: LastPassGroup
metadata:
  labels:
    app.kubernetes.io/name: lastpass-operator
    app.kubernetes.io/managed-by: kustomize
  name: lastpassgroup-sample
spec:
  # required
  groupRef:
    # optional (default "")
    group: SampleGroup
    # optional (default false)
    withUsername: true
    # optional (default false)
    withPassword: true
    # optional (default false)
    withUrl: true
    # optional (default false)
    withNote: true
  # optional
  syncPolicy:
    # required (default false)
    enabled: true
    # required (in seconds)
    refresh: 60
