apiVersion: edgelevel.com/v1alpha1
kind: LastPass
metadata:
  labels:
    app.kubernetes.io/name: lastpass-operator
    app.kubernetes.io/managed-by: kustomize
  name: lastpass-sample
spec:
  # required
  secretRef:
    # optional (default "")
    group: SampleGroup
    # required
    name: Saample
    # optional (default false)
    withUsername: true
    # optional (default false)
    withPassword: true
    # optional (default false)
    withUrl: true
    # optional (default false)
    withNote: true
  # optional
  syncPolicy:
    # required (default false)
    enabled: true
    # required (in seconds)
    refresh: 60
